# Generated by Django 4.1.2 on 2022-10-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_lyric_alter_artist_first_name_alter_artist_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_released',
            field=models.DateField(),
        ),
    ]
